services:

  backend:
    build: ./node-backend
    ports:
      - "8080:8080"
    volumes:
      - ./node-backend:/usr/src/app

  frontend:
    build: ./react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./react-frontend/src:/usr/src/app/src